### ISSUE TITLE
Not able to install on EVOQ Basic 9.6.4

### ISSUE THREAD

**Issue by denisjoconnor** [w8tcha/dnnsitemapui#2]
Can this update be used for EVOQ Basic as well, 9.6.4 is the latest version?

**Comment by w8tcha** [comment]
The current release will only work with dnn 9.8 or newer

**Comment by denisjoconnor** [comment]
OK but will there be a similar release for EVOQ Basic? We need to replace if so as currently the version we have on EVOQ has a lot of permission checks for each tab and our sitemap page has a lot of tabs which results in very high server response times when page first loaded for entire site. Thanks

**Comment by w8tcha** [comment]
No sorry evoq is not supported. i can only test this with dnn. Evoq is not a free product, and its impossible to test this.

But it would also not work in dnn. TThe permission checks are needed, Since each tab can have different permissions.  I  dont think there would be a different solution.

**Comment by denisjoconnor** [comment]
I was not suggesting removing permission checks but optimizing them as the sitemap module takes very long time to load when there are a lot of tabs. EVOQ may be obtained as a trial on request but if you are not supporting this module for EVOQ then that is fine. We will try to use the DDR menu as a replacement which also has permission checks but doesn't cause these load time issues. Note your earlier version releases work on EVOQ only this latest version 9.8 release does not. Thanks

**Comment by w8tcha** [comment]
I take a look at the ddr menu source what they do different? Why does the current version doesnt work?

**Comment by denisjoconnor** [comment]
We may have installed originally on dnn and upgraded to evoq so if its not supported then that's fine. Note we removed it and used the basic sitemap ddr menu (https://www.dnnsoftware.com/wiki/ddrmenu-user-guide) i.e. <ddr:MENU MenuStyle="..." runat="server" /> in the skin and the load times have since improved significantly. Maybe you could take a look at the difference in page load of your module and out of box ddr in terms of permission checks etc but we can close this issue now. Thanks
